name = "mypinkshop-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "mypinkshop-db"
database_id = "YOUR_D1_DATABASE_ID_HERE"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "mypinkshop-images"

[vars]
JWT_SECRET = "mypinkshop-super-secret-key-2026"
